### ISSUE TITLE
Không có mã lỗi khi thanh toán không thành công

### ISSUE THREAD

**Issue by trongtran97** [naustudio/node-vn-payments#15]
Chào team, mình có sử dụng cổng thanh toán Ngân Lượng trong dự án của mình, tuy nhiên khi thanh toán thất bại, mình không thấy mã lỗi hay thông báo lỗi ở trong response trả về. Mong sớm được team hổ trợ.
![Uploading Screen Shot 2019-04-24 at 00.58.14.png…](response)

**Comment by trongthanh** [comment]
Bạn cài vn-payments@1.1.0 và test xem đã hết lỗi chưa. Nếu chưa thì reopen.
